### ISSUE TITLE
Feature: Visualize Existing Config Files

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/visual-config-editor#10]
# Visualize Existing CircleCI Config Files
Create visual and editable diagrams for existing CircleCI configuration files so that existing users can make use of the Visual Config Editor, or come back to make additional changes in the future.

# Blocked By Issue

The CircleCI Config SDK, the critical library powering the visual config editor to generate CircleCI Config does not yet possess the ability to parse configuration files. Once this issue has been resolved, config files can be parsed and visualized.

Blocked by: https://github.com/CircleCI-Public/circleci-config-sdk-ts/issues/52

**Comment by Jaryt** [comment]
Loading existing config files is now supported
