### ISSUE TITLE
Bug: `macos.x86.medium.gen2` resource not accepted when doing an import

### ISSUE THREAD

**Issue by mathaeus** [CircleCI-Public/visual-config-editor#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When uploading our current existing valid circleCI config, the VCE throws an error that the `macos.x86.medium.gen2` resource is not a valid enum case.

<img width="587" alt="Screenshot 2022-09-08 at 16 10 42" src="https://user-images.githubusercontent.com/5389635/189146460-ee518906-8a0b-4084-8315-d0c6160e72f0.png">

### Minimum reproduction code

https://gist.github.com/mathaeus/2ff2b1d2782977e639ad9746cabc914c

### Steps to reproduce

Just import an existing config with that executor

### Expected behavior

Valid circleCI executors are also accepted by the VCE.

### CircleCI Config SDK version

Whatever the [online editor](https://circleci-public.github.io/visual-config-editor/) gave me:

```
# This configuration has been automatically generated by the CircleCI Config SDK.
# For more information, see https://github.com/CircleCI-Public/circleci-config-sdk-ts
# SDK Version: 0.9.0-alpha.16
# VCE Version: v0.10.5
# Modeled with the CircleCI visual config editor.
# For more information, see https://github.com/CircleCI-Public/visual-config-editor
```

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by adamdmharvey** [comment]
Looks like upstream work to address this via https://github.com/CircleCI-Public/circleci-config-sdk-ts/pull/145 ; just helping tie them together.
