### ISSUE TITLE
Feature: Action toast

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/visual-config-editor#72]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When an action happens, there should be a toast that confirms the action was successful.

![image](https://user-images.githubusercontent.com/2455550/145598596-027d00d1-e4e4-4c55-b7cd-4fade1999b4c.png)

### Teachability, documentation, adoption, migration strategy

This should be documented in pages where this action occurs.

### What is the motivation / use case for changing the behavior?

To inform the user when they made a change. May provide undo actions as well.

**Comment by jliby** [comment]
Has been implemented!!!
